### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by nttylock** [zinedkaloc/ai-travel-planner#2]
~ % git clone git@github.com:zinedkaloc/ai-travel-planner.git
Cloning into 'ai-travel-planner'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights.

**Comment by zinedkaloc** [comment]
Thank you for reporting. It's working fine as shown below. With SSH, you may need to configure your terminal. Here's an image for reference: 

<img width="541" alt="image" src="https://github.com/zinedkaloc/ai-travel-planner/assets/104208669/8c82e791-8cc8-4894-88b4-28f880b9e0ff">

Additionally, you have the option to use HTTPS to clone the repository. Please refer to the command below:

```sh
git clone https://github.com/zinedkaloc/ai-travel-planner.git
```

Let me know if you need further assistance!

**Comment by nttylock** [comment]
Thanks you so much. Got it via git clone https://github.com/zinedkaloc/ai-travel-planner.git
You're the best. Appreciated.
